### ISSUE TITLE
Unable to connect to quickbook

### ISSUE THREAD

**Issue by abhijith-b** [IntuitDeveloper/SampleApp-PHP-for-OpenId-OAuth-V3APICalls#1]
App Throws error "NetworkError: 403 Forbidden -https://appcenter.intuit.com/trackapi/TrackingActions?remote=true... "  when try to connect to quickbook using the button  'connect to quickbook'

**Comment by skodamarthi** [comment]
This is a known issue with intuit.ipp.anywhere.js for some users. Please check https://intuitdeveloper.lc.intuit.com/questions/979928-403-forbidden-from-intuit-ipp-anywhere-js

The resolution would be to replace the intuit.ipp.anywhere.js link in index.php file at line 11 from “https://appcenter.intuit.com/Content/IA/intuit.ipp.anywhere.js" to "https://js.appcenter.intuit.com/Content/IA/intuit.ipp.anywhere-1.3.0.js” The new link is for the latest intuit.ipp.anywhere.js file.

Also, the user should have read, write and execute permissions to all the files in the PHPSample folder and should login with valid Intuit account credentials to connect the app to Quickbooks.
